#
# batesste-time-machine.dc.yml
#

services:

  tm-app:
    image: mbentley/timemachine:smb
    hostname: batesste-time-machine
    container_name: batesste-time-machine
    networks:
      - batesste-time-machine
    restart: always
    volumes:
      - batesste-time-machine:/opt/timemachine
    env_file: .batesste-time-machine-env
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "445:445"

  tm-backup:
    image: offen/docker-volume-backup:latest
    hostname: batesste-time-machine-backup
    container_name: batesste-time-machine-backup
    restart: always
    env_file:
      - .backup.env
      - .aws.creds.env
    volumes:
      - batesste-time-machine:/backup/time-machine-backup:ro
    depends_on:
      - tm-app
    networks:
      - batesste-time-machine

volumes:
   batesste-time-machine:
     external: true
     name: batesste-time-machine

networks:
  batesste-time-machine:
    driver: bridge
