{
 "title": "iCloud",
 "tags": [
  "icloud",
  "location"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "server_name",
    "label": "Server",
    "query": {
     "query": "label_values(icloud_auth_2fa_update_needed, server_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "2FA Status",
   "type": "stat",
   "description": "A indicator the inform us if the 2FA needs to be renewed.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "icloud_auth_2fa_update_needed{server_name=\"$server_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iCloud Photos",
   "type": "stat",
   "description": "The total number of photos stored on iCloud",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "icloud_photos_total_photos{server_name=\"$server_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iCloud Contacts",
   "type": "stat",
   "description": "The total number of contacts stored on iCloud",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "icloud_contacts_total_contacts{server_name=\"$server_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iCloud Device Location",
   "type": "geomap",
   "description": "This panel shows the location of certain devices we can track via iCloud.",
   "gridPos": { "h": 16, "w": 22, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "icloud_location_latitude{server_name=\"$server_name\", device=~\"iphone.*|ipad.*\"}",
     "legendFormat": "lat-{{device}}"
    },
    {
     "expr": "icloud_location_longtitude{server_name=\"$server_name\", device=~\"iphone.*|ipad.*\"}",
     "legendFormat": "long-{{device}}"
    }
   ]
  },
  {
   "title": "Device Latitude",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "icloud_location_latitude{server_name=\"$server_name\",device=~\"iphone.*|ipad.*\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Device Longitude",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "icloud_location_longtitude{server_name=\"$server_name\",device=~\"iphone.*|ipad.*\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}