#!/bin/bash

MYDOMAIN=${MYDOMAIN:-raithlin.com}
MYHOSTNAME=${MYHOSTNAME:-gateway}
GDAPIKEY=${GDAPIKEY:-none}
LOGDEST=${LOGDEST:-local7.info}

if [ $GDAPIKEY == "none" ]; then
    echo "Error, you must provide the GoDaddy API Key (GDAPIKEY=<key:secret>)!"
    exit 1
fi

MYIP=`curl -s "https://api.ipify.org"`
DNSDATA=`curl -s -X GET -H "Authorization: sso-key ${GDAPIKEY}" "https://api.ote-godaddy.com/v1/domains/${MYDOMAIN}/records/A/${MYHOSTNAME}"`
GDIP=`echo $DNSDATA | cut -d ',' -f 1 | tr -d '"' | cut -d ":" -f 2`

echo "`date '+%Y-%m-%d %H:%M:%S'` - Current External IP is $MYIP, GoDaddy DNS IP is $GDIP"

#if [ "$GDIP" != "$MYIP" -a "$MYIP" != "" ]; then
#    echo "IP has changed!! Updating on GoDaddy"
#    curl -s -X PUT "https://api.ote-godaddy.com/v1/domains/${MYDOMAIN}/records/A/${MYHOSTNAME}" -H "Authorization: sso-key ${GDAPIKEY}" -H "Content-Type: application/json" -d "[{\"data\": \"${MYIP}\"}]"
#    logger -p $LOGDEST "Changed IP on ${hostname}.${MYDOMAIN} from ${GDIP} to ${MYIP}"
#fi
