{
 "title": "Emporia SmartPlugs Dashboard",
 "description": "A summary dashboard for the Emporia smartplugs in my home.",
 "tags": [
  "emporia",
  "power",
  "smart-home"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Outside Lights",
   "type": "gauge",
   "description": "Emporia smartplug connected to outside lights.",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snoc_pinewood_plug_a_power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Home Office",
   "type": "gauge",
   "description": "Emporia smartplug connected to computer stuff in living room.",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snoc_pinewood_plug_b_power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Living Room Light",
   "type": "gauge",
   "description": "Emporia smartplug connected to tall lamp in living room beside the wood-burning stove.",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snoc_pinewood_plug_c_power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "snoc-thinkstation",
   "type": "gauge",
   "description": "Emporia smartplug connected to snoc-thinkstation.",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snoc_pinewood_plug_d_power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Playstation",
   "type": "gauge",
   "description": "Emporia smartplug connected to Oisin's PlayStation",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snoc_pinewood_plug_e_power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Master Bedroom - Stevie",
   "type": "gauge",
   "description": "Emporia smartplug connected to Master Bedroom outlet on Stevie's side.",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snoc_pinewood_plug_f_power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Master Bedroom - Ang",
   "type": "gauge",
   "description": "Emporia smartplug connected to bedside outlet on Ang's side of the bed.",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snoc_pinewood_plug_g_power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "snoc-beelink",
   "type": "gauge",
   "description": "Emporia smartplug connected to my Beelink home server.",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "snoc_pinewood_plug_h_power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Energy Consumption vs Time",
   "type": "timeseries",
   "description": "A time-series for all the detected Emporia smartplugs that plots energy (in Joules) versus time.",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    { "expr": "snoc_pinewood_plug_a_power", "legendFormat": "__auto" },
    { "expr": "snoc_pinewood_plug_b_power", "legendFormat": "__auto" },
    { "expr": "snoc_pinewood_plug_c_power", "legendFormat": "__auto" },
    { "expr": "snoc_pinewood_plug_d_power", "legendFormat": "__auto" },
    { "expr": "snoc_pinewood_plug_e_power", "legendFormat": "__auto" },
    { "expr": "snoc_pinewood_plug_f_power", "legendFormat": "__auto" },
    { "expr": "snoc_pinewood_plug_g_power", "legendFormat": "__auto" },
    { "expr": "snoc_pinewood_plug_h_power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SmartpPug State vs Time",
   "type": "timeseries",
   "description": "This shows when a given smartplug has been ON of OFF. Note that when ON it may draw no power depending on its load.",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "snoc_pinewood_plug_a_on{snoc_pinewood_plug_a_on=\"on\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snoc_pinewood_plug_b_on{snoc_pinewood_plug_b_on=\"on\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snoc_pinewood_plug_c_on{snoc_pinewood_plug_c_on=\"on\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snoc_pinewood_plug_d_on{snoc_pinewood_plug_d_on=\"on\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snoc_pinewood_plug_e_on{snoc_pinewood_plug_e_on=\"on\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snoc_pinewood_plug_f_on{snoc_pinewood_plug_f_on=\"on\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snoc_pinewood_plug_g_on{snoc_pinewood_plug_g_on=\"on\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snoc_pinewood_plug_h_on{snoc_pinewood_plug_h_on=\"on\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}