name: batesste-homesetup
on:
 pull_request:
   paths:
     - '**.md'

jobs:
  spellcheck-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Perform hack to get Linkspector to work on Ubuntu 24.04
        run: |
          echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
      - name: GitHub spellcheck action
        uses: rojopolis/spellcheck-github-actions@0.45.0
      - name: Run Linkspector with reviewdog
        uses: UmbrellaDocs/action-linkspector@v1.2.4
