name: batesste-homesetup
on:
  pull_request:
    paths:
      - 'time-machine/**'

jobs:
  time-machine-test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./time-machine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Create .aws.creds.env file
        run: |
          echo "AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"" > .aws.creds.env
          echo "AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"" >> .aws.creds.env
      - name: Create the external docker volume
        run: docker volume create batesste-time-machine
      - name: Docker Compose based smoke-test
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          compose-file: batesste-time-machine.dc.yml
          cwd: ./time-machine
